spring:
  application:
    name: generic-api
  datasource:    
    url: jdbc:mysql://localhost:3306/catalogo_db?useTimezone=true&serverTimezone=America/Sao_Paulo
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
    max-active: 5
    test-on-borrow: true
    validation-query: SELECT 1
    test-while-idle: true
  jpa:
    database: mysql
    show-sql: true
    properties:
      hibernate:
        hbm2ddl:
          auto: update          
        temp:
          use_jdbc_metadata_defaults: true
server:
  port: 8080